### PR TITLE
fix typos and add option replace

### PR DESCRIPTION
**Pull request by sylvainbaronnet**

### CODE REVIEW

**Comment by maximkoretskiy** [comment]
@sylvainbaronnet Hi. Thank You for PR. It would be better if 
- You create separate PR for grammar improvements.
- You create some tests for `option: replace`

**Comment by sylvainbaronnet** [comment]
Hey @maximkoretskiy,

I'm not very familiar with merge request workflow, those automatically merge into one PR. Not sure how to split them...

I will add some test.

**Comment by maximkoretskiy** [comment]
Can You describe usecase when `replace` is required?

**Comment by sylvainbaronnet** [comment]
Not really a use case but a matter of performance : less size / less rules for the same result.

**Comment by sylvainbaronnet** [comment]
@maximkoretskiy test added (sry for multiple commit)

**Comment by sylvainbaronnet** [comment]
Thank you very much for the merge, can you push the new version to npm please ?

**Comment by maximkoretskiy** [comment]
@sylvainbaronnet done)

**Pull request merged**
